name: Documentation
on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Documentation
      uses: eagletrt/documentation@main
      with:
        author: Harrison Prest           # project author
        project: Prova python  # project name
        rootfile: Title            # project title
        folders: ../ASD.py ../ASD.js ../config_parser.h         # path of folders and files you want to document
        version: 1.0.0             # project version
        release: 1.0.0             # project release
        language: js                # language used
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        nojekyll: true
        branch: docs # The branch the action should deploy to.
        folder: docs/_build # The folder the action should deploy.
